apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: templates.smtp.saas
spec:
  group: smtp.saas
  names:
    kind: Template
    listKind: TemplateList
    plural: templates
    singular: template
  scope: Namespaced
  version: v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smtp-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: smtp-operator
  template:
    metadata:
      labels:
        name: smtp-operator
    spec:
      containers:
        - name: smtp-operator
          image: batazor/smtp-operator:6
          command:
          - smtp-operator
          imagePullPolicy: Always
